var series = {
  title: 'Accel World', //Series title
  cover: 'http://cdn.myanimelist.net/images/manga/1/52761.jpg',
  year: '2010-', //year published
  authors: ['Reki Kawahara'],
  artists: ['Hiroyuki Aigamo'],
  publisher: "Yen Press",
  status: 'ongoing', //Whether the series is still running or not
  genres: ['Action', 'Romance', 'School', 'Sci-Fi', 'Shounen'],
  aliases: ['アクセル・ワールド'],
  rating: 7.69, //The rating on myanimelist. Not necessarily applicable
  description: "No matter what age it is, the 'Bullied Child' will never disappear. The overweight, Middle School student, Haruyuki, was one such kid. The only time he could relax completely, was when he would play a squash game on the local network the school had set up. He loved playing this simple game as he can forget painful times while immersed in it. It was fall. He was passing his time like this until one day, he had an encounter with the school's most beautiful, refined girl, 'Snow Black', which changed his life abruptly. Introduced to the software she transmitted, Haruyuki learned about 'Accel World.' A program that enhances one's mind capabilities, with certain side-effects. It was the moment the guy on the lowest rung at school became 'Burst Linker,' protecting the Princess as her knight. - Based on a light novel series by Kawahara Reki.  (Source: MU).", //Self explanitory. May also be called synopsis
};

var comic = {
  series_id: "12064632somealphanumericnumber23562352", //Unique ID of the series. Generated by nedb
  series_title: 'Accel World', //In case the series is unknown
  subtitle: '', //The title of the issue or volume
  cover: '', //If this isn't available tries the series cover, then the first image in the file
  issue: 1, //The issue #
  chapter: 1, //The chapter number
  volume: 0,
  release: "September 2014", //The date the volume/issue was released

  relative_path: '/Manga/Accel World/Accel World Chapter 001.cbz' //the path to the comic file relative to the comics directory
};