function comic(series_title, subtitle, cover, issue, chapter, volume, release, relative_path, media_type) {
  //_id: undefined, //Unique ID of the series. Generated by nedb
  this.series_title = series_title; //In case the series is unknown
  this.subtitle = subtitle; //The title of the issue or volume
  this.cover = cover; //If this isn't available tries the series cover, then the first image in the file
  this.issue = issue; //The issue #
  this.chapter = chapter; //The chapter number
  this.volume = volume;
  this.release = release; //The date the volume/issue was released

  this.relative_path = relative_path; //the path to the comic file relative to the comics directory
  this.media_type = media_type; //The type of media (ie. Manga, Comic, Light Novel, etc)
}

module.exports = comic;