module.exports = {
  //_id: undefined, //Unique ID of the series. Generated by nedb
  series_title: undefined, //In case the series is unknown
  subtitle: undefined, //The title of the issue or volume
  cover: undefined, //If this isn't available tries the series cover, then the first image in the file
  issue: undefined, //The issue #
  chapter: undefined, //The chapter number
  volume: undefined,
  release: undefined, //The date the volume/issue was released

  relative_path: undefined //the path to the comic file relative to the comics directory
};